services:
  frontend:
    build:
      context: ./chef-claude
    image: frontend
    ports:
      - '3000:80'
  backend:
    build:
      context: ./backend
    image: backend
    ports:
      - '8000:8000'